force-app/main/default/objects/Departure_Date__c/Departure_Date__c.object-meta.xml
<CustomObject>
    <label>Departure Date</label>
    <nameField>
        <label>Departure Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departure Date</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Items__c/Order_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Order Line Items</label>
    <nameField>
        <label>Order Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Order_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Items__c</fullName>
    <label>Order Line Items</label>
    <referenceTo>Order_Line_Items__c</referenceTo>
    <relationshipLabel>Passenger</relationshipLabel>
    <relationshipName>Passenger</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/recordTypes/Guided.recordType-meta.xml
<RecordType>
    <fullName>Guided</fullName>
    <active>true</active>
    <label>Guided</label>
</RecordType>

force-app/main/default/objects/Trip__c/recordTypes/self_guided.recordType-meta.xml
<RecordType>
    <fullName>self_guided</fullName>
    <active>true</active>
    <label>self guided</label>
</RecordType>

force-app/main/default/objects/Trip_Option__c/Trip_Option__c.object-meta.xml
<CustomObject>
    <label>Trip Option</label>
    <nameField>
        <label>Trip Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>trip options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Option__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>trip options</relationshipLabel>
    <relationshipName>trip_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/getOLIwithOrderAmountTestClass.cls
@isTest
public class getOLIwithOrderAmountTestClass {

    @isTest
    public static void tesMethod1Insert(){
        
       //list<RecordType> RCTOrder = AuswalkUtilsApexClass.getRecordType('Self Guided');
        //system.debug('RCTOrder: '+RCTOrder);
        
        //create trip 
        Trip__c trip = TestDataFactoryApexClass.createTrip('Self_Guided');
        insert trip;
        system.debug('trip: '+trip.id);
        
        //create trip option
        Trip_Option__c tripOption = TestDataFactoryApexClass.createTripOption(trip.Id, 'Self Guided');
        insert tripOption;
        system.debug('tripOption: '+tripOption.id);
        
        //create departure date
        Departure_Date__c DepartureDate = TestDataFactoryApexClass.createDepartureDate(tripOption.id);
        insert DepartureDate;
        system.debug('DepartureDate: '+DepartureDate.id);
        
        Orders__c order = TestDataFactoryApexClass.createOrder('Self Guided', trip.id, tripOption.id, DepartureDate.id);
        insert order;
        system.debug('order: '+order.id);
        
        //create Order_Line_Items__c
        Order_Line_Items__c orderLineItems = TestDataFactoryApexClass.createorderLineItems(order.id,DepartureDate.Id);
        insert orderLineItems;
        system.debug('orderLineItems: '+orderLineItems.id);
        
        
        //create Passenger
        Passenger__c Passenger = TestDataFactoryApexClass.createPassenger(orderLineItems.id, order.id);
        insert Passenger;
		system.debug('orderLineItems: '+orderLineItems.id);
        
        
        
    }
}