force-app/main/default/objects/Departure_Date__c/Departure_Date__c.object-meta.xml
<CustomObject>
    <label>Departure Date</label>
    <nameField>
        <label>Departure Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departure Date</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Items__c/Order_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Order Line Items</label>
    <nameField>
        <label>Order Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Auswalk-Github/force-app/main/default/objects/Order_Line_Items__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Order_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Items__c</fullName>
    <label>Order Line Items</label>
    <referenceTo>Order_Line_Items__c</referenceTo>
    <relationshipLabel>Passenger</relationshipLabel>
    <relationshipName>Passenger</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/aus_AdditionalOLIWebservice.cls
@RestResource(urlMapping='/additionalOLI')
global with sharing class aus_AdditionalOLIWebservice {
    
    global class mainWrapper{
        global String orderName {get;set;}
        global String firstName {get;set;}
        global String lastName {get;set;}
        global String passengerEmail {get;set;}
        global String roomType {get;set;}
        
    }
    
    @HttpPost
    global static String additionalOLI(){
        
        String stringToBeReturned;
        RestRequest req = RestContext.request;
        String requestBodyString = req.requestBody.tostring();        
        mainWrapper mainWrap = (mainWrapper)JSON.deserialize(requestBodyString, mainWrapper.class);
         system.debug('mainWrap20' +mainWrap);
        
        Orders__c order= new Orders__c();
        order = [Select Id,Name, Departure_Date__c  from Orders__c where Name =: mainWrap.orderName ];
        system.debug('order22' +order);
        Order_Line_Items__c newOrderLineItem = new Order_Line_Items__c();
        newOrderLineItem.Orders__c = order.Id;
        newOrderLineItem.Status__c = 'On Hold';
        newOrderLineItem.Departure_Date__c = order.Departure_Date__c;
        insert newOrderLineItem;
        
        Passenger__c primaryPax = new Passenger__c();
        primaryPax.Name = mainWrap.firstName;
        primaryPax.Last_Name__c = mainWrap.lastName;
        primaryPax.Email__c = mainWrap.passengerEmail;
        primaryPax.Order_Line_Items__c = newOrderLineItem.Id;
        primaryPax.Orders__c = order.Id;
        primaryPax.Passenger_Type__c = mainWrap.roomType;
        insert primaryPax;
        stringToBeReturned = order.Id+';'+order.Name;
        
        return stringToBeReturned;
    } 
    
    
}